package constants;

import server.potentials.ItemPotentialTierType;

/**
 *
 * @author Lloyd Korn
 */
public class ItemConstants {

    // Equips
    public static final int CRUSADER_CODEX = 1172000;

    // Use
    public static final int COMBO_PARADE1 = 2023484,
            COMBO_PARADE2 = 2023494,
            COMBO_PARADE3 = 2023495,
            RETURN_SCROLL_NEAREST_TOWN = 2030000,
            MIRACLE_CUBE_FRAGMENT = 2430112,
            SUPER_MIRACLE_CUBE_FRAGMENT = 2430481,
            BONUS_POTENTIAL_CUBE_FRAGMENT = 2430915,
            MEMORY_CUBE_FRAGMENT = 2431445,
            RED_CUBE_FRAGMENT = 2431893,
            BLACK_CUBE_FRAGMENT = 2431894,
            VIOLET_CUBE_FRAGMENT = 2434125,
            //
            ADVANCED_POTENTIAL_SCROLL = 2049400,
            POTENTIAL_SCROLL = 2049401,
            SPECIAL_POTENTIAL_SCROLL = 2049402,
            SPECIAL_POTENTIAL_SCROLL_2 = 2049406,
            ADVANCED_POTENTIAL_SCROLL_2 = 2049407,
            POTENTIAL_SCROLL_2 = 2049408,
            ADVANCED_POTENTIAL_SCROLL_3 = 2049412,
            ADVANCED_POTENTIAL_SCROLL_4 = 2049413,
            POTENTIAL_SCROLL_FOR_PURPLE_SOUL_RINGS = 2049414,
            POTENTIAL_SCROLL_FOR_BLUE_SOUL_RINGS = 2049415,
            POTENTIAL_SCROLL_3 = 2049416,
            SPECIAL_POTENTIAL_SCROLL_3 = 2049417,
            SPECIAL_POTENTIAL_SCROLL_4 = 2049419,
            HEART_NECKLACE_POTENTIAL_SCROLL = 2049421,
            POTENTIAL_SCROLL_FOR_CALTON_MUSTACHE = 2049424,
            POTENTIAL_SCROLL_FOR_BOUNTY_ROOKIE_SUNGLASSES = 2049427,
            POTENTIAL_SCROLL_FOR_BOUNTY_HUNTER_SUNGLASSES = 2049428,
            POTENTIAL_SCROLL_FOR_BOUNTY_VERTERAN_SUNGLASSES = 2049429,
            POTENTIAL_SCROLL_FOR_BOUNTY_MASTER_SUNGLASSES = 2049430,
            POTENTIAL_SCROLL_FOR_BOUNTY_LEGEND_SUNGLASSES = 2049431,
            POTENTIAL_SCROLL_FOR_BOUNTY_ROOKIE_EARRINGS = 2049432,
            POTENTIAL_SCROLL_FOR_BOUNTY_HUNTER_EARRINGS = 2049433,
            POTENTIAL_SCROLL_FOR_BOUNTY_VERTERAN_EARRINGS = 2049434,
            POTENTIAL_SCROLL_FOR_BOUNTY_MASTER_EARRINGS = 2049435,
            POTENTIAL_SCROLL_FOR_BOUNTY_LEGEND_EARRINGS = 2049436,
            POTENTIAL_SCROLL_FOR_BOUNTY_ROOKIE_RING = 2049437,
            POTENTIAL_SCROLL_FOR_BOUNTY_HUNTER_RING = 2049438,
            POTENTIAL_SCROLL_FOR_BOUNTY_VERTERAN_RING = 2049439,
            POTENTIAL_SCROLL_FOR_BOUNTY_MASTER_RING = 2049440,
            POTENTIAL_SCROLL_FOR_BOUNTY_LEGEND_RING = 2049441,
            POTENTIAL_SCROLL_FOR_BOUNTY_ROOKIE_NECKLACE = 2049442,
            POTENTIAL_SCROLL_FOR_BOUNTY_HUNTER_NECKLACE = 2049443,
            POTENTIAL_SCROLL_FOR_BOUNTY_VERTERAN_NECKLACE = 2049444,
            POTENTIAL_SCROLL_FOR_BOUNTY_MASTER_NECKLACE = 2049445,
            POTENTIAL_SCROLL_FOR_BOUNTY_LEGEND_NECKLACE = 2049446,
            POTENTIAL_SCROLL_4 = 2049449,
            POTENTIAL_SCROLL_FOR_TOT_HELMET = 2049452,
            //
            EPIC_POTENTIAL_SCROLL_100 = 2049700,
            EPIC_POTENTIAL_SCROLL_80 = 2049701,
            EPIC_POTENTIAL_SCROLL_100_2 = 2049702,
            EPIC_POTENTIAL_SCROLL_100_3 = 2049703,
            EPIC_POTENTIAL_SCROLL_40 = 2049704,
            EPIC_POTENTIAL_SCROLL_50 = 2049705,
            EPIC_POTENTIAL_SCROLL_100_4 = 2049706,
            EPIC_POTENTIAL_SCROLL_40_2 = 2049707,
            EPIC_POTENTIAL_SCROLL_50_2 = 2049708,
            VISION_EPIC_POTENTIAL_SCROLL_50 = 2049709,
            EPIC_POTENTIAL_SCROLL_50_3 = 2049710,
            UNIQUE_POTENTIAL_SCROLL_80 = 2049750,
            UNIQUE_POTENTIAL_SCROLL_60 = 2049751,
            UNIQUE_POTENTIAL_SCROLL_30 = 2049752,
            UNIQUE_POTENTIAL_SCROLL_80_2 = 2049753,
            UNIQUE_POTENTIAL_SCROLL_60_2 = 2049754,
            UNIQUE_POTENTIAL_SCROLL_30_2 = 2049755,
            UNIQUE_POTENTIAL_SCROLL_30_3 = 2049756,
            UNIQUE_POTENTIAL_SCROLL_50 = 2049757,
            UNIQUE_POTENTIAL_SCROLL_50_2 = 2049758,
            UNIQUE_POTENTIAL_SCROLL_100 = 2049762,
            UNIQUE_POTENTIAL_SCROLL_100_2 = 2049764,
            //
            OCCULT_CUBE_UNTRADEABLE = 2710000,
            MASTER_CRAFTMANS_CUBE = 2710002,
            MEISTER_CUBE = 2710003,
            HERMES_CUBE = 2710005,
            //
            OCCULT_CUBE = 2711000,
            OCCULT_CUBE_UNTRADEABLE2 = 2711001,
            TIMIC_CUBE = 2711002,
            MASTER_CRAFTMANS_CUBE2 = 2711003,
            MEISTER_CUBE2 = 2711004,
            MASTER_CRAFTMANS_CUBE_UNTRADEABLE = 2711005,
            MEISTER_CUBE_UNTRADEABLE = 2711006,
            MAPLE_SAINT_WEAPON_CUBE = 2711007,
            UNK_CUBE = 2711008,
            OCCULT_CUBE_UNTRADEABLE3 = 2711009,
            //
            SPECIAL_BONUS_POTENTIAL_SCROLL = 2048306;
    // Cash
    public static final int BONUS_POTENTIAL_CUBE = 5062500,
            MIRACLE_CUBE = 5062000,
            SUPER_MIRACLE_CUBE = 5062002,
            RED_CUBE = 5062009,
            BLACK_CUBE = 5062010,
            VIOLET_CUBE = 5062024,
            MEMORY_CUBE = 5062090,
            PERFECT_POTENTIAL_STAMP = 5062300,
            PENDANT_SLOT_EXPANSION = 5550000,
            PENDANT_SLOT_EXPANSION_7DAYS = 5550001,
            PENDANT_SLOT_EXPANSION_2 = 5550002,
            PENDANT_SLOT_EXPANSION_90DAYS = 5550003;

    ///////////////////
    public static ItemPotentialTierType getPotentialTierFromScrollId(int scrollId) {
        switch (scrollId) {
            case ADVANCED_POTENTIAL_SCROLL:
            case POTENTIAL_SCROLL:
            case SPECIAL_POTENTIAL_SCROLL:
            case SPECIAL_POTENTIAL_SCROLL_2:
            case ADVANCED_POTENTIAL_SCROLL_2:
            case POTENTIAL_SCROLL_2:
            case ADVANCED_POTENTIAL_SCROLL_3:
            case ADVANCED_POTENTIAL_SCROLL_4:
            case POTENTIAL_SCROLL_FOR_PURPLE_SOUL_RINGS:
            case POTENTIAL_SCROLL_FOR_BLUE_SOUL_RINGS:
            case POTENTIAL_SCROLL_3:
            case SPECIAL_POTENTIAL_SCROLL_3:
            case SPECIAL_POTENTIAL_SCROLL_4:
            case HEART_NECKLACE_POTENTIAL_SCROLL:
            case POTENTIAL_SCROLL_FOR_CALTON_MUSTACHE:
            case POTENTIAL_SCROLL_FOR_BOUNTY_ROOKIE_SUNGLASSES:
            case POTENTIAL_SCROLL_FOR_BOUNTY_HUNTER_SUNGLASSES:
            case POTENTIAL_SCROLL_FOR_BOUNTY_VERTERAN_SUNGLASSES:
            case POTENTIAL_SCROLL_FOR_BOUNTY_MASTER_SUNGLASSES:
            case POTENTIAL_SCROLL_FOR_BOUNTY_LEGEND_SUNGLASSES:
            case POTENTIAL_SCROLL_FOR_BOUNTY_ROOKIE_EARRINGS:
            case POTENTIAL_SCROLL_FOR_BOUNTY_HUNTER_EARRINGS:
            case POTENTIAL_SCROLL_FOR_BOUNTY_VERTERAN_EARRINGS:
            case POTENTIAL_SCROLL_FOR_BOUNTY_MASTER_EARRINGS:
            case POTENTIAL_SCROLL_FOR_BOUNTY_LEGEND_EARRINGS:
            case POTENTIAL_SCROLL_FOR_BOUNTY_ROOKIE_RING:
            case POTENTIAL_SCROLL_FOR_BOUNTY_HUNTER_RING:
            case POTENTIAL_SCROLL_FOR_BOUNTY_VERTERAN_RING:
            case POTENTIAL_SCROLL_FOR_BOUNTY_MASTER_RING:
            case POTENTIAL_SCROLL_FOR_BOUNTY_LEGEND_RING:
            case POTENTIAL_SCROLL_FOR_BOUNTY_ROOKIE_NECKLACE:
            case POTENTIAL_SCROLL_FOR_BOUNTY_HUNTER_NECKLACE:
            case POTENTIAL_SCROLL_FOR_BOUNTY_VERTERAN_NECKLACE:
            case POTENTIAL_SCROLL_FOR_BOUNTY_MASTER_NECKLACE:
            case POTENTIAL_SCROLL_FOR_BOUNTY_LEGEND_NECKLACE:
            case POTENTIAL_SCROLL_4:
            case POTENTIAL_SCROLL_FOR_TOT_HELMET:
                return ItemPotentialTierType.Rare_Hidden;
            case EPIC_POTENTIAL_SCROLL_100:
            case EPIC_POTENTIAL_SCROLL_80:
            case EPIC_POTENTIAL_SCROLL_100_2:
            case EPIC_POTENTIAL_SCROLL_100_3:
            case EPIC_POTENTIAL_SCROLL_40:
            case EPIC_POTENTIAL_SCROLL_50:
            case EPIC_POTENTIAL_SCROLL_100_4:
            case EPIC_POTENTIAL_SCROLL_40_2:
            case EPIC_POTENTIAL_SCROLL_50_2:
            case VISION_EPIC_POTENTIAL_SCROLL_50:
            case EPIC_POTENTIAL_SCROLL_50_3:
                return ItemPotentialTierType.Epic_Hidden;
            case UNIQUE_POTENTIAL_SCROLL_80:
            case UNIQUE_POTENTIAL_SCROLL_60:
            case UNIQUE_POTENTIAL_SCROLL_30:
            case UNIQUE_POTENTIAL_SCROLL_80_2:
            case UNIQUE_POTENTIAL_SCROLL_60_2:
            case UNIQUE_POTENTIAL_SCROLL_30_2:
            case UNIQUE_POTENTIAL_SCROLL_30_3:
            case UNIQUE_POTENTIAL_SCROLL_50:
            case UNIQUE_POTENTIAL_SCROLL_50_2:
            case UNIQUE_POTENTIAL_SCROLL_100:
            case UNIQUE_POTENTIAL_SCROLL_100_2:
                return ItemPotentialTierType.Unique_Hidden;
        }
        return ItemPotentialTierType.None;
    }

    public static boolean isPotentialScroll(int scrollId) {
        switch (scrollId) {
            case SPECIAL_BONUS_POTENTIAL_SCROLL:

            case ADVANCED_POTENTIAL_SCROLL:
            case POTENTIAL_SCROLL:
            case SPECIAL_POTENTIAL_SCROLL:
            case SPECIAL_POTENTIAL_SCROLL_2:
            case ADVANCED_POTENTIAL_SCROLL_2:
            case POTENTIAL_SCROLL_2:
            case ADVANCED_POTENTIAL_SCROLL_3:
            case ADVANCED_POTENTIAL_SCROLL_4:
            case POTENTIAL_SCROLL_FOR_PURPLE_SOUL_RINGS:
            case POTENTIAL_SCROLL_FOR_BLUE_SOUL_RINGS:
            case POTENTIAL_SCROLL_3:
            case SPECIAL_POTENTIAL_SCROLL_3:
            case SPECIAL_POTENTIAL_SCROLL_4:
            case HEART_NECKLACE_POTENTIAL_SCROLL:
            case POTENTIAL_SCROLL_FOR_CALTON_MUSTACHE:
            case POTENTIAL_SCROLL_FOR_BOUNTY_ROOKIE_SUNGLASSES:
            case POTENTIAL_SCROLL_FOR_BOUNTY_HUNTER_SUNGLASSES:
            case POTENTIAL_SCROLL_FOR_BOUNTY_VERTERAN_SUNGLASSES:
            case POTENTIAL_SCROLL_FOR_BOUNTY_MASTER_SUNGLASSES:
            case POTENTIAL_SCROLL_FOR_BOUNTY_LEGEND_SUNGLASSES:
            case POTENTIAL_SCROLL_FOR_BOUNTY_ROOKIE_EARRINGS:
            case POTENTIAL_SCROLL_FOR_BOUNTY_HUNTER_EARRINGS:
            case POTENTIAL_SCROLL_FOR_BOUNTY_VERTERAN_EARRINGS:
            case POTENTIAL_SCROLL_FOR_BOUNTY_MASTER_EARRINGS:
            case POTENTIAL_SCROLL_FOR_BOUNTY_LEGEND_EARRINGS:
            case POTENTIAL_SCROLL_FOR_BOUNTY_ROOKIE_RING:
            case POTENTIAL_SCROLL_FOR_BOUNTY_HUNTER_RING:
            case POTENTIAL_SCROLL_FOR_BOUNTY_VERTERAN_RING:
            case POTENTIAL_SCROLL_FOR_BOUNTY_MASTER_RING:
            case POTENTIAL_SCROLL_FOR_BOUNTY_LEGEND_RING:
            case POTENTIAL_SCROLL_FOR_BOUNTY_ROOKIE_NECKLACE:
            case POTENTIAL_SCROLL_FOR_BOUNTY_HUNTER_NECKLACE:
            case POTENTIAL_SCROLL_FOR_BOUNTY_VERTERAN_NECKLACE:
            case POTENTIAL_SCROLL_FOR_BOUNTY_MASTER_NECKLACE:
            case POTENTIAL_SCROLL_FOR_BOUNTY_LEGEND_NECKLACE:
            case POTENTIAL_SCROLL_4:
            case POTENTIAL_SCROLL_FOR_TOT_HELMET:

            case EPIC_POTENTIAL_SCROLL_100:
            case EPIC_POTENTIAL_SCROLL_80:
            case EPIC_POTENTIAL_SCROLL_100_2:
            case EPIC_POTENTIAL_SCROLL_100_3:
            case EPIC_POTENTIAL_SCROLL_40:
            case EPIC_POTENTIAL_SCROLL_50:
            case EPIC_POTENTIAL_SCROLL_100_4:
            case EPIC_POTENTIAL_SCROLL_40_2:
            case EPIC_POTENTIAL_SCROLL_50_2:
            case VISION_EPIC_POTENTIAL_SCROLL_50:
            case EPIC_POTENTIAL_SCROLL_50_3:
            case UNIQUE_POTENTIAL_SCROLL_80:
            case UNIQUE_POTENTIAL_SCROLL_60:
            case UNIQUE_POTENTIAL_SCROLL_30:
            case UNIQUE_POTENTIAL_SCROLL_80_2:
            case UNIQUE_POTENTIAL_SCROLL_60_2:
            case UNIQUE_POTENTIAL_SCROLL_30_2:
            case UNIQUE_POTENTIAL_SCROLL_30_3:
            case UNIQUE_POTENTIAL_SCROLL_50:
            case UNIQUE_POTENTIAL_SCROLL_50_2:
            case UNIQUE_POTENTIAL_SCROLL_100:
            case UNIQUE_POTENTIAL_SCROLL_100_2:
                return true;
        }
        return false;
    }

    public static final boolean isDualBladeWeapon(final int itemId) {
        return itemId / 10000 == 134;
    }

    public static final boolean isEmblem(int itemId) {
        return itemId / 10000 == 119;
    }

    public static final boolean isTotem(int itemId) {
        return itemId / 10000 == 120;
    }

    public static boolean IsArcaneSymbol(int nItemID) {
        return nItemID >= 1712000 && nItemID <= 1712003;
    }
}
