package database;

import com.mchange.v2.c3p0.ComboPooledDataSource;
import com.mchange.v2.c3p0.DataSources;
import java.sql.Connection;
import java.sql.SQLException;

/**
 * Represents a database object that gives out connections for use to
 * the service software.
 * 
 * @author Zygon
 */
public class Database {

    static {
        try {
            Class.forName("com.mysql.jdbc.Driver"); // touch the driver first
        } catch (Exception e) {
            System.err.println("SEVERE : SQL Driver has not been located during runtime. Please make sure it is in the correct path.");
            System.exit(0);
        }
    }
    
    private ComboPooledDataSource cSrc;
    
    private Database(String url, String user, String pass) throws SQLException {
        cSrc = new ComboPooledDataSource();
        cSrc.setJdbcUrl(url);
        cSrc.setUser(user);
        cSrc.setPassword(pass);
        cSrc.setIdleConnectionTestPeriod(1800); // try to check every 30 minutes, tune this later
    }
    
    /**
     * Gets a connection for use to the database.
     * 
     * @return a connection to the desired database.
     */
    public Connection GetConnection() {
        try {
            return cSrc.getConnection();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    /**
     * Closes this database object.  This includes all
     * connections generated by this object.
     * 
     * @throws SQLException
     */
    public void Close() throws SQLException {
        DataSources.destroy(cSrc);
    }
    
    public static Database CreateDatabase(String url, String user, String pass) {
        Database ret = null;
        try {
            ret = new Database(url, user, pass);
        } catch (Exception e) {
            System.out.println("[SEVERE] Unable to generate a Database object.  Check to make sure the driver is in the correct location and the required libraries are in your classpath as well.");
        }
        return ret;
    }
}
